### PR TITLE
added save_instances_inventory

### PR DESCRIPTION
**Pull request by jameswnl**
This will supercede #9

### CODE REVIEW

**Comment by agrare** [comment]
This looks fine but I think you need to add `save_inventory_cloud` [here](https://github.com/agrare/foreman_providers/blob/master/app/models/providers/ems_refresh/save_inventory.rb#L12)

**Comment by jameswnl** [comment]
@agrare I've overridden the `save_inventory` https://github.com/jameswnl/foreman_providers/blob/cf584b80e2ac6dca7ad2a0f2657f6a83ace03131/app/models/providers/ems_refresh/refresher.rb#L70-L70

**Comment by agrare** [comment]
That's the refresher though, that just calls back into the main `EmsRefresh.save_inventory`

**Comment by jameswnl** [comment]
@agrare see my updates

**Review by agrare — APPROVED** [review]

**Pull request merged**
